default_language_version:
    python: python3

repos:
-   repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: .bumpversion.cfg
    - id: flake8
      additional_dependencies: ["flake8-string-format"]
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, develop, --branch, master]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.0"
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@2.1.2", "prettier-plugin-solidity@1.0.0-beta.1"]
        files: "\\.sol$"
        args: ["--plugin=prettier-plugin-solidity"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 977b5b383e7b3f65f21b94300f4d7
  hooks:
  - id: mypy
    args: []
    entry: mypy .
    pass_filenames: false
